main: pyin.txt
	./main
	python3 main.py < pyin.txt
pyin.txt:
	gcc main.c -o main
clean:
	rm -f main pyin.txt out.txt

# histogram: main
# 	./main < cin.txt | python3 main.py
# main:
# 	gcc main.c -o main
# clean:
# 	rm -f main

# main: 
# 	gcc main.c -o main
# 	./main
# clean:
# 	rm -f main out.txt